### ISSUE TITLE
Missing splash screen

### ISSUE THREAD

**Issue by scvcrem** [dirtyhawk/stata-integration#8]
Hi, thanks this script is great! One puzzling thing I just encountered is that when I launch Stata from the launcher installed by the script the session opens without the usual splash screen that appears if I launch it from the terminal. Do you have any idea of why this is happening and how to fix it? I am running Ubuntu 22.04. I attach screenshots of what I get when running from launcher and running from terminal.
![Screenshot from 2024-05-27 23-38-30](https://github.com/dirtyhawk/stata-integration/assets/27969339/889d5bc5-4802-4173-9cd3-3b26017cbef2)
![screenshot_anonymized](https://github.com/dirtyhawk/stata-integration/assets/27969339/faecabd6-5db5-46cd-97fc-7beae8092805)

**Comment by scvcrem** [comment]
I solved the issue by editing the line "Exec=/usr/local/stata/xstata-se -q" in "/usr/share/applications/stata-stata18_windowed.desktop" to "Exec=/usr/local/stata/xstata-se"

**Comment by scvcrem** [comment]
I solved the issue by editing the line "Exec=/usr/local/stata/xstata-se -q" in "/usr/share/applications/stata-stata18_windowed.desktop" to "Exec=/usr/local/stata/xstata-se"

**Comment by dirtyhawk** [comment]
Hi @scvcrem , and thanks for reaching out. Sorry for the late reply. Indeed, when I originally wrote the script, this was intended behaviour: I don't like the splash screen very much, and added the `-q` parameter. Removing it is completely fine. I will make the parameter optional via the script when I do a next update.

All the best!
